###################################################################
### Config file for data pipeline blueprints
###################################################################
FeedName: Descriptive name for data product
ConfigVersion: v6.25.0
DataArea: Infrastructure
DataGovernanceArea: Infrastructure
SubjectAreaCode: PLO
Purpose: Description of what this data product does

Ingestion:
  - FeedNumber: 1
    SensitivityData: []
    RetentionPolicy: KEEP-1
    GlacierPolicy: KEEP-1
    IngestionInfo:
      IngestionType: FileDrop
      Authentication:
        AuthenticationType: user
    InboundPrefix: pg_blueprint_test
    FileInfo:
      FileType: csv
      Header: infer
      AdditionalArgs:
        sep: ','

Transformation:
  - TransformationType: python-lambda
    FeedNumber: []
    LambdaInfo:
      LambdaType: LOOKUP
      LambdaName: RawToCleaned

  - TransformationType: dbt-snowflake

###################################################################
### Snowflake config - see .tftest.hcl files in the tests folder
###################################################################
Snowflake:
  # env: ${env}           # implicitly the deployment environment
  # location: BA_IRELAND  # our default Snowflake instance

  service_user:
    - name: MY_SERVICE_USER # NOTE: gets an implicit _${env} suffix
      location: BA_LONDON
      comment: Not quite sure, core-infra creates a DBT_CUST_LOY_BA_MEMBERS_${env}

  # NB: warehouses are not related to environments
  warehouse: # defaults to single cluster XSMALL
    - name: WH_TEST1
      size: MEDIUM

    - name: WH_TEST1
      size: LARGE
      clusters: 2

    # can even change parameters across Snowflake locations
    - name: WH_TEST1
      location: [ba_london, ba_bangkok] # demonstrating case insensitivity
      size: x-large
      comment: Special extra large warehouse for London
      clusters: 3

  database:
    - name: DB_THING1 # NOTE: gets an implicit _${env} suffix
      env: dev # demonstrating single list entry as a string
      extra_schemas: [VIEWS_EI, VIEWS_IB, VIEWS_IAG]

    - name: DB_THING2
      env: [UAT, PRD] # only deploy to these environments
      location: [ba_london, ba_ireland]
      comment: Database for something special in London uat & production only

  # these create S3 storage integrations and external stage(s)
  # role always seems to be aws-location/ba-olympus-snowflake ?
  integration:
    - name: INT_INTEGRATION # NOTE: gets an implicit _${env} suffix
      env: uat
      buckets:
        - BA_OLYMPUS_${env}_CLEANED/
        - BA_OLYMPUS_${env}_ALIGNED/
        - BA_OLYMPUS_${env}_RAW/
      stage:
        - name: STG_STAGE1 # NOTE: gets an implicit _${env} suffix
          bucket: BA_OLYMPUS_${env}_ALIGNED/ # has to be one of the allowed ones ?
          comment: Stage for something or other

        - name: STG_STAGE2
          bucket: BA_OLYMPUS_${env}_RAW/
          comment: Stage for something or other

###################################################################
### Airflow config
###################################################################
Airflow:
  - DagName: pg_blueprint_test_dbt
